import heroUrl from "~/assets/images/Home/hero.webp";

export const roadmapData = {
  totalCountText: "48 lộ trình nghề nghiệp",
  tabs: ["Phổ biến", "Mới nhất", "Nhiều lượt xem nhất"],
  levelSelectLabel: "Tất cả trình độ",

  items: [
    {
      id: "roadmap-1",
      statusLabel: "HOT",
      level: "beginner",
      title: "Frontend Web Developer",
      description: "Xây dựng giao diện người dùng hiện đại và mượt mà với ReactJS & TailwindCSS.",
      tags: ["REACT", "TAILWIND", "JS (ES6)"],
      actionText: "Khám phá lộ trình",
      viewsNum: 15400,
      createdAt: "2026-01-15",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-2",
      statusLabel: "",
      level: "intermediate",
      title: "Backend Engineer",
      description: "Làm chủ server, cơ sở dữ liệu và API. Xây dựng hệ thống Microservices hiện đại.",
      tags: ["NODEJS", "POSTGRESQL", "DOCKER"],
      actionText: "Khám phá lộ trình",
      viewsNum: 12300,
      createdAt: "2026-02-10",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-3",
      statusLabel: "MỚI",
      level: "beginner",
      title: "UI/UX Product Designer",
      description: "Thiết kế trải nghiệm người dùng tuyệt vời với Figma và phương pháp User Research.",
      tags: ["FIGMA", "USER RESEARCH", "PROTOTYPE"],
      actionText: "Khám phá lộ trình",
      viewsNum: 8900,
      createdAt: "2026-03-25",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-4",
      statusLabel: "",
      level: "advanced",
      title: "Data Scientist & AI Engineer",
      description: "Khám phá sức mạnh của dữ liệu, xây dựng mô hình Học máy và Trí tuệ nhân tạo.",
      tags: ["PYTHON", "PANDAS", "MACHINE LEARNING"],
      actionText: "Khám phá lộ trình",
      viewsNum: 11200,
      createdAt: "2026-03-01",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-5",
      statusLabel: "HOT",
      level: "intermediate",
      title: "Fullstack Web Developer",
      description: "Làm chủ trọn bộ kỹ năng phát triển ứng dụng Web từ Frontend đến Backend & DevOps.",
      tags: ["NEXTJS", "NESTJS", "PRISMA"],
      actionText: "Khám phá lộ trình",
      viewsNum: 19800,
      createdAt: "2026-04-01",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-6",
      statusLabel: "MỚI",
      level: "advanced",
      title: "DevOps & Cloud Architect",
      description: "Tự động hóa chu trình CI/CD, quản trị hạ tầng trên AWS và Kubernetes.",
      tags: ["KUBERNETES", "AWS", "TERRAFORM"],
      actionText: "Khám phá lộ trình",
      viewsNum: 9400,
      createdAt: "2026-04-10",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-7",
      statusLabel: "",
      level: "beginner",
      title: "Mobile App Developer (Flutter)",
      description: "Xây dựng ứng dụng di động đa nền tảng iOS & Android chỉ với 1 codebase duy nhất.",
      tags: ["FLUTTER", "DART", "FIREBASE"],
      actionText: "Khám phá lộ trình",
      viewsNum: 7800,
      createdAt: "2026-02-20",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-8",
      statusLabel: "",
      level: "intermediate",
      title: "Cyber Security Specialist",
      description: "Bảo vệ hệ thống thông tin, phân tích lỗ hổng bảo mật và phòng chống tấn công mạng.",
      tags: ["NETWORK", "PENTEST", "LINUX"],
      actionText: "Khám phá lộ trình",
      viewsNum: 6500,
      createdAt: "2026-01-30",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-9",
      statusLabel: "HOT",
      level: "beginner",
      title: "Python Web Developer",
      description: "Phát triển web siêu nhanh với Django & FastAPI kết hợp cơ sở dữ liệu quan hệ.",
      tags: ["PYTHON", "DJANGO", "FASTAPI"],
      actionText: "Khám phá lộ trình",
      viewsNum: 13500,
      createdAt: "2026-03-10",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-10",
      statusLabel: "",
      level: "advanced",
      title: "AI & Large Language Models (LLM)",
      description: "Xây dựng ứng dụng AI thông minh với LangChain, RAG và tinh chỉnh mô hình LLM.",
      tags: ["LANGCHAIN", "OPENAI", "VECTOR DB"],
      actionText: "Khám phá lộ trình",
      viewsNum: 16200,
      createdAt: "2026-04-15",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-11",
      statusLabel: "MỚI",
      level: "beginner",
      title: "Software QA / Automated Testing",
      description: "Đảm bảo chất lượng phần mềm với Selenium, Playwright và kiểm thử tự động.",
      tags: ["PLAYWRIGHT", "JEST", "CI/CD"],
      actionText: "Khám phá lộ trình",
      viewsNum: 5200,
      createdAt: "2026-04-05",
      imageUrl: heroUrl,
    },
    {
      id: "roadmap-12",
      statusLabel: "",
      level: "intermediate",
      title: "Embedded Systems & IoT Engineer",
      description: "Lập trình vi điều khiển C/C++, cảm biến và xây dựng ứng dụng Internet of Things.",
      tags: ["C/C++", "ESP32", "MQTT"],
      actionText: "Khám phá lộ trình",
      viewsNum: 4800,
      createdAt: "2026-01-05",
      imageUrl: heroUrl,
    },
  ],

  suggestions: [
    {
      id: "roadmap-sugg-1",
      title: "Giao diện & Trải nghiệm",
      description:
        "Yêu thích cái đẹp, sự tỉ mỉ và mong muốn tạo ra sản phẩm chạm đến người dùng.",
      iconName: "Eye",
    },
    {
      id: "roadmap-sugg-2",
      title: "Logic & Hệ thống",
      description:
        "Đam mê giải quyết các bài toán hóc búa, tối ưu hóa hiệu suất và xây dựng kiến trúc.",
      iconName: "Code",
    },
    {
      id: "roadmap-sugg-3",
      title: "Dữ liệu",
      description:
        "Tìm kiếm những sự thật ẩn giấu trong các con số và dự đoán tương lai bằng AI.",
      iconName: "Database",
    },
    {
      id: "roadmap-sugg-4",
      title: "Toàn diện",
      description:
        "Mong muốn làm chủ cả Frontend lẫn Backend để tự tay xây dựng sản phẩm từ A-Z.",
      iconName: "Layers",
    },
  ],

  faqs: [
    {
      id: "roadmap-faq-1",
      question: "Làm thế nào để biết tôi hợp với Frontend hay Backend?",
      answer: "Hãy thử sức với dự án nhỏ ở cả 2 mảng. Nếu thích thiết kế và phản hồi thị giác ngay, hãy chọn Frontend; nếu thích logic xử lý ngầm và cơ sở dữ liệu, hãy chọn Backend.",
    },
    {
      id: "roadmap-faq-2",
      question: "Một lộ trình mất bao lâu để hoàn thành?",
      answer: "Thời gian trung bình từ 3 đến 6 tháng tùy thuộc vào thời gian bạn dành ra học tập mỗi ngày.",
    },
    {
      id: "roadmap-faq-3",
      question: "Lộ trình có bao gồm dự án thực tế không?",
      answer: "Tất cả các lộ trình tại LearnFlow đều đi kèm dự án thực chiến tốt nghiệp để làm đẹp portfolio của bạn.",
    },
  ],
};
