import heroUrl from "~/assets/images/Home/hero.webp";

export const courseData = {
  categories: ["Tất cả", "Frontend", "Backend", "Data Science"],

  items: [
    {
      id: "course-1",
      category: "Frontend",
      level: "Cơ bản",
      title: "JavaScript nền tảng cho người mới",
      description:
        "Làm quen với ngôn ngữ lập trình phổ biến nhất thế giới và xây dựng dự án đầu tay.",
      lessonsCount: "12 bài",
      studentsCount: "2.5k",
      studentsNum: 2500,
      rating: 4.9,
      createdAt: "2026-01-15",
      imageUrl: heroUrl,
    },
    {
      id: "course-2",
      category: "Frontend",
      level: "Trung cấp",
      title: "ReactJS thực chiến ứng dụng",
      description: "Xây dựng các ứng dụng web hiện đại với ReactJS, Hooks và Redux Toolkit.",
      lessonsCount: "24 bài",
      studentsCount: "1.8k",
      studentsNum: 1800,
      rating: 4.8,
      createdAt: "2026-02-10",
      imageUrl: heroUrl,
    },
    {
      id: "course-3",
      category: "Backend",
      level: "Nâng cao",
      title: "Cấu trúc dữ liệu và giải thuật",
      description: "Nâng tầm tư duy lập trình và chinh phục các bài toán thuật toán nâng cao.",
      lessonsCount: "30 bài",
      studentsCount: "1.2k",
      studentsNum: 1200,
      rating: 4.9,
      createdAt: "2026-03-01",
      imageUrl: heroUrl,
    },
    {
      id: "course-4",
      category: "Backend",
      level: "Trung cấp",
      title: "Node.js Backend nền tảng",
      description: "Làm chủ JavaScript ở phía Server và xây dựng RESTful APIs chuyên nghiệp.",
      lessonsCount: "18 bài",
      studentsCount: "900",
      studentsNum: 900,
      rating: 4.7,
      createdAt: "2026-01-20",
      imageUrl: heroUrl,
    },
    {
      id: "course-5",
      category: "Data Science",
      level: "Cơ bản",
      title: "Python cho Data Science & AI",
      description: "Học Python từ con số 0, khai phá dữ liệu với Pandas, NumPy và Matplotlib.",
      lessonsCount: "20 bài",
      studentsCount: "1.5k",
      studentsNum: 1500,
      rating: 4.85,
      createdAt: "2026-02-28",
      imageUrl: heroUrl,
    },
    {
      id: "course-6",
      category: "Data Science",
      level: "Trung cấp",
      title: "Phân tích dữ liệu & Machine Learning",
      description: "Ứng dụng các thuật toán Học máy phổ biến để dự đoán và phân tích dữ liệu.",
      lessonsCount: "25 bài",
      studentsCount: "1.1k",
      studentsNum: 1100,
      rating: 4.75,
      createdAt: "2026-03-15",
      imageUrl: heroUrl,
    },
    {
      id: "course-7",
      category: "Frontend",
      level: "Nâng cao",
      title: "TypeScript Chuyên Sâu & Architecture",
      description: "Làm chủ Type System, Generics và áp dụng Design Patterns trong dự án lớn.",
      lessonsCount: "22 bài",
      studentsCount: "2.1k",
      studentsNum: 2100,
      rating: 4.95,
      createdAt: "2026-04-01",
      imageUrl: heroUrl,
    },
    {
      id: "course-8",
      category: "Backend",
      level: "Nâng cao",
      title: "Docker & Kubernetes Microservices",
      description: "Đóng gói ứng dụng, triển khai container và quản lý hạ tầng đám mây hiện đại.",
      lessonsCount: "28 bài",
      studentsCount: "1.6k",
      studentsNum: 1600,
      rating: 4.9,
      createdAt: "2026-04-10",
      imageUrl: heroUrl,
    },
    {
      id: "course-9",
      category: "Frontend",
      level: "Trung cấp",
      title: "Next.js App Router Masterclass",
      description: "Tối ưu SEO, Server Components và Server Actions chuyên nghiệp với Next.js.",
      lessonsCount: "26 bài",
      studentsCount: "2.8k",
      studentsNum: 2800,
      rating: 4.98,
      createdAt: "2026-04-15",
      imageUrl: heroUrl,
    },
    {
      id: "course-10",
      category: "Backend",
      level: "Cơ bản",
      title: "SQL & Thiết kế Cơ sở Dữ liệu",
      description: "Làm chủ PostgreSQL, MySQL và các kỹ thuật tối ưu hóa truy vấn nâng cao.",
      lessonsCount: "16 bài",
      studentsCount: "3.2k",
      studentsNum: 3200,
      rating: 4.88,
      createdAt: "2026-03-20",
      imageUrl: heroUrl,
    },
    {
      id: "course-11",
      category: "Data Science",
      level: "Nâng cao",
      title: "Deep Learning & Computer Vision",
      description: "Xây dựng mô hình Mạng Nơ-ron nhân tạo và xử lý ảnh với PyTorch & OpenCV.",
      lessonsCount: "32 bài",
      studentsCount: "950",
      studentsNum: 950,
      rating: 4.92,
      createdAt: "2026-04-05",
      imageUrl: heroUrl,
    },
    {
      id: "course-12",
      category: "Frontend",
      level: "Cơ bản",
      title: "HTML5, CSS3 & Responsive Design",
      description: "Xây dựng giao diện trang web chuẩn SEO, đáp ứng mọi kích thước màn hình.",
      lessonsCount: "14 bài",
      studentsCount: "4.1k",
      studentsNum: 4100,
      rating: 4.91,
      createdAt: "2026-01-05",
      imageUrl: heroUrl,
    },
  ],

  benefits: [
    {
      id: "benefit-1",
      title: "Học từ nền tảng",
      description:
        "Kiến thức được hệ thống bài bản, giúp bạn hiểu rõ bản chất cốt lõi thay vì chỉ học vẹt code.",
      iconName: "Award",
    },
    {
      id: "benefit-2",
      title: "Kết hợp Roadmap",
      description:
        "Mọi khóa học đều nằm trong lộ trình nghề nghiệp rõ ràng, định hướng tương lai cho bạn.",
      iconName: "Compass",
    },
    {
      id: "benefit-3",
      title: "Luyện tập Challenge",
      description:
        "Hệ thống bài tập thực hành và thử thách ngay trong trình duyệt giúp bạn nhớ lâu hơn.",
      iconName: "Cpu",
    },
  ],

  faqs: [
    {
      id: "faq-1",
      question: "Khóa học có dành cho người chưa biết gì về code không?",
      answer:
        "Có, các khóa học gắn tag 'Cơ bản' được thiết kế chi tiết dành riêng cho người mới bắt đầu từ con số 0.",
    },
    {
      id: "faq-2",
      question: "Tôi có được nhận chứng chỉ sau khi hoàn thành khóa học không?",
      answer:
        "Có, sau khi hoàn thành 100% bài học và vượt qua bài test cuối khóa, bạn sẽ nhận được chứng chỉ kỹ thuật số.",
    },
    {
      id: "faq-3",
      question: "Tôi có thể xem lại bài học khi đã kết thúc khóa học không?",
      answer:
        "Tài khoản của bạn được cấp quyền truy cập trọn đời, bạn có thể xem lại video và tài liệu bất cứ lúc nào.",
    },
  ],
};
