// Mock data for Submissions Page (Lịch sử nộp bài)

export const mockSubmissionsData = [
  // Contest A / Problem 1 submissions
  {
    id: "#10294",
    problemId: "1",
    problemTitle: "Two Sum (Hai số tổng)",
    contestId: "A",
    contestTitle: "Weekly Coding Challenge #45",
    status: "Accepted",
    statusCode: "AC",
    language: "Python 3",
    runtime: "54 ms",
    memory: "16.2 MB",
    submittedAt: "10 phút trước",
    score: "100/100",
  },
  {
    id: "#10293",
    problemId: "2",
    problemTitle: "Add Two Numbers (Cộng hai số)",
    contestId: "A",
    contestTitle: "Weekly Coding Challenge #45",
    status: "Wrong Answer",
    statusCode: "WA",
    language: "C++ 17",
    runtime: "N/A",
    memory: "N/A",
    submittedAt: "1 giờ trước",
    score: "60/100",
  },
  {
    id: "#10292",
    problemId: "3",
    problemTitle: "Longest Substring Without Repeating Characters",
    contestId: "A",
    contestTitle: "Weekly Coding Challenge #45",
    status: "Time Limit Exceeded",
    statusCode: "TLE",
    language: "Java 11",
    runtime: "2005 ms",
    memory: "42.1 MB",
    submittedAt: "3 giờ trước",
    score: "30/100",
  },
  {
    id: "#10290",
    problemId: "5",
    problemTitle: "Graph Bipartite Checking",
    contestId: "A",
    contestTitle: "Weekly Coding Challenge #45",
    status: "Compilation Error",
    statusCode: "CE",
    language: "C++ 17",
    runtime: "-",
    memory: "-",
    submittedAt: "2 ngày trước",
    score: "0/100",
  },
  {
    id: "#10288",
    problemId: "2",
    problemTitle: "Add Two Numbers (Cộng hai số)",
    contestId: "A",
    contestTitle: "Weekly Coding Challenge #45",
    status: "Runtime Error",
    statusCode: "RE",
    language: "Python 3",
    runtime: "88 ms",
    memory: "22.5 MB",
    submittedAt: "4 ngày trước",
    score: "20/100",
  },
  // Contest B / Other problem submissions
  {
    id: "#10291",
    problemId: "4",
    problemTitle: "Median of Two Sorted Arrays",
    contestId: "B",
    contestTitle: "Beginner Algorithm Contest 2026",
    status: "Accepted",
    statusCode: "AC",
    language: "JavaScript",
    runtime: "112 ms",
    memory: "48.3 MB",
    submittedAt: "Hôm qua",
    score: "100/100",
  },
  {
    id: "#10289",
    problemId: "1",
    problemTitle: "Two Sum (Hai số tổng)",
    contestId: "B",
    contestTitle: "Beginner Algorithm Contest 2026",
    status: "Accepted",
    statusCode: "AC",
    language: "C++ 20",
    runtime: "36 ms",
    memory: "16.4 MB",
    submittedAt: "3 ngày trước",
    score: "100/100",
  },
];
