export const mockContestListData = {
  tabs: ["Tất cả", "Đang diễn ra", "Sắp tới", "Đã kết thúc"],
  contests: [
    {
      id: "15",
      status: "LIVE",
      statusLabel: "ĐANG DIỄN RA",
      title: "FySet Weekly Contest 15",
      participants: "1,240",
      writers: "FySet Team",
      startTime: "Running Now",
      duration: "90 min",
      actionType: "join",
      actionLabel: "Tham gia ngay",
      problemsPreview: [
        { id: "A", title: "Array Sum Difference", difficulty: "Dễ", points: 500 },
        { id: "B", title: "Binary Search Tree Validation", difficulty: "Trung bình", points: 1000 },
        { id: "C", title: "Dynamic Programming - Coin Change", difficulty: "Trung bình", points: 1500 },
        { id: "D", title: "Graph Shortest Path - Dijkstra", difficulty: "Khó", points: 2000 },
      ],
    },
    {
      id: "16",
      status: "UPCOMING",
      statusLabel: "SẮP DIỄN RA",
      title: "Algorithm Master Challenge 2026",
      participants: "850",
      writers: "Master_Coder",
      startTime: "Oct 25, 20:00",
      duration: "120 min",
      actionType: "register",
      actionLabel: "Đăng ký tham gia",
      problemsPreview: [
        { id: "A", title: "String Anagram Detection", difficulty: "Dễ", points: 400 },
        { id: "B", title: "Subarray Sum Equals K", difficulty: "Trung bình", points: 1000 },
        { id: "C", title: "Lowest Common Ancestor in Tree", difficulty: "Trung bình", points: 1200 },
        { id: "D", title: "Sliding Window Maximum", difficulty: "Khó", points: 1800 },
      ],
    },
    {
      id: "17",
      status: "UPCOMING",
      statusLabel: "SẮP DIỄN RA",
      title: "Frontend Speed Coding Sprint",
      participants: "420",
      writers: "SteveStack",
      startTime: "Nov 12, 19:30",
      duration: "60 min",
      actionType: "register",
      actionLabel: "Đăng ký tham gia",
      problemsPreview: [
        { id: "A", title: "Debounce Function Implementation", difficulty: "Dễ", points: 500 },
        { id: "B", title: "Custom React Hook for LocalStorage", difficulty: "Trung bình", points: 1000 },
        { id: "C", title: "Virtual DOM Diffing Algorithm", difficulty: "Khó", points: 2000 },
      ],
    },
    {
      id: "14",
      status: "FINISHED",
      statusLabel: "ĐÃ KẾT THÚC",
      title: "Monthly Coding Sprint - Sept",
      participants: "2,100",
      writers: "FySet Team",
      startTime: "Sept 30, 2024",
      duration: "180 min",
      actionType: "standings",
      actionLabel: "Xem bảng xếp hạng →",
      problemsPreview: [
        { id: "A", title: "Two Sum", difficulty: "Dễ", points: 300 },
        { id: "B", title: "Valid Parentheses", difficulty: "Dễ", points: 400 },
        { id: "C", title: "Merge K Sorted Lists", difficulty: "Khó", points: 1500 },
        { id: "D", title: "Trapping Rain Water", difficulty: "Khó", points: 2000 },
      ],
    },
    {
      id: "13",
      status: "FINISHED",
      statusLabel: "ĐÃ KẾT THÚC",
      title: "Data Structures Cup #4",
      participants: "1,650",
      writers: "Algo_Expert",
      startTime: "Aug 15, 2024",
      duration: "120 min",
      actionType: "standings",
      actionLabel: "Xem bảng xếp hạng →",
      problemsPreview: [
        { id: "A", title: "LRU Cache Implementation", difficulty: "Trung bình", points: 1000 },
        { id: "B", title: "Red-Black Tree Insertion", difficulty: "Khó", points: 2000 },
      ],
    },
  ],
};
