export const problemListData = {
  hero: {
    title: "Thư viện Bài tập",
    description:
      "Nâng cao kỹ năng lập trình của bạn với hàng ngàn bài tập từ cơ bản đến nâng cao. Khám phá các thử thách để rèn luyện tư duy logic và cấu trúc dữ liệu.",
  },

  filters: {
    difficulties: [
      { id: "all", label: "Tất cả độ khó" },
      { id: "easy", label: "Dễ" },
      { id: "medium", label: "Trung bình" },
      { id: "hard", label: "Khó" },
    ],
    topics: [
      { id: "all", label: "Tất cả chủ đề" },
      { id: "array", label: "Mảng" },
      { id: "string", label: "Chuỗi" },
      { id: "linked-list", label: "Danh sách liên kết" },
      { id: "hash-table", label: "Hash Table" },
      { id: "binary-search", label: "Binary Search" },
      { id: "tree", label: "Cây & Đồ thị" },
      { id: "dp", label: "Quy hoạch động" },
    ],
    languages: [
      { id: "all", label: "Tất cả ngôn ngữ" },
      { id: "cpp", label: "C++" },
      { id: "java", label: "Java" },
      { id: "python", label: "Python" },
      { id: "js", label: "JavaScript" },
      { id: "go", label: "Go" },
    ],
    statuses: [
      { id: "all", label: "Tất cả trạng thái" },
      { id: "solved", label: "Đã giải" },
      { id: "attempted", label: "Đang thử" },
      { id: "unsolved", label: "Chưa giải" },
    ],
  },

  items: [
    {
      id: 1,
      number: 1,
      title: "Two Sum",
      slug: "two-sum",
      level: "Dễ",
      acceptance: "52%",
      tags: ["Mảng", "Hash Table"],
      status: "solved",
    },
    {
      id: 2,
      number: 2,
      title: "Add Two Numbers",
      slug: "add-two-numbers",
      level: "Trung bình",
      acceptance: "40%",
      tags: ["Danh sách liên kết", "Math"],
      status: "unsolved",
    },
    {
      id: 3,
      number: 3,
      title: "Longest Substring Without Repeating Characters",
      slug: "longest-substring-without-repeating-characters",
      level: "Trung bình",
      acceptance: "34%",
      tags: ["Hash Table", "Chuỗi", "Sliding Window"],
      status: "attempted",
    },
    {
      id: 4,
      number: 4,
      title: "Median of Two Sorted Arrays",
      slug: "median-of-two-sorted-arrays",
      level: "Khó",
      acceptance: "35%",
      tags: ["Mảng", "Binary Search", "Chia để trị"],
      status: "unsolved",
    },
    {
      id: 5,
      number: 5,
      title: "Longest Palindromic Substring",
      slug: "longest-palindromic-substring",
      level: "Trung bình",
      acceptance: "32%",
      tags: ["Chuỗi", "Quy hoạch động"],
      status: "solved",
    },
    {
      id: 6,
      number: 6,
      title: "Zigzag Conversion",
      slug: "zigzag-conversion",
      level: "Trung bình",
      acceptance: "45%",
      tags: ["Chuỗi"],
      status: "unsolved",
    },
    {
      id: 7,
      number: 7,
      title: "Reverse Integer",
      slug: "reverse-integer",
      level: "Trung bình",
      acceptance: "27%",
      tags: ["Math"],
      status: "solved",
    },
    {
      id: 8,
      number: 8,
      title: "String to Integer (atoi)",
      slug: "string-to-integer-atoi",
      level: "Trung bình",
      acceptance: "17%",
      tags: ["Chuỗi"],
      status: "attempted",
    },
    {
      id: 9,
      number: 9,
      title: "Palindrome Number",
      slug: "palindrome-number",
      level: "Dễ",
      acceptance: "54%",
      tags: ["Math"],
      status: "solved",
    },
    {
      id: 10,
      number: 10,
      title: "Regular Expression Matching",
      slug: "regular-expression-matching",
      level: "Khó",
      acceptance: "28%",
      tags: ["Chuỗi", "Quy hoạch động", "Recursion"],
      status: "unsolved",
    },
    {
      id: 11,
      number: 11,
      title: "Container With Most Water",
      slug: "container-with-most-water",
      level: "Trung bình",
      acceptance: "54%",
      tags: ["Mảng", "Two Pointers", "Greedy"],
      status: "solved",
    },
    {
      id: 12,
      number: 12,
      title: "Integer to Roman",
      slug: "integer-to-roman",
      level: "Trung bình",
      acceptance: "62%",
      tags: ["Hash Table", "Math", "Chuỗi"],
      status: "unsolved",
    },
  ],
};
