import heroUrl from "~/assets/images/Home/hero.webp";

export const leaderboardData = {
  tabs: ["Tổng xếp hạng", "Challenge", "Contest", "Streak", "Roadmap"],

  podium: [
    {
      id: "leaderboard-1",
      rank: 2,
      name: "Minh Quân",
      points: "11,250 điểm",
      exp: 11250,
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-2",
      rank: 1,
      name: "Khánh Vy",
      points: "12,500 điểm",
      exp: 12500,
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-3",
      rank: 3,
      name: "Hoàng Nam",
      points: "10,800 điểm",
      exp: 10800,
      avatarUrl: heroUrl,
    },
  ],

  rankings: [
    {
      id: "leaderboard-4",
      rank: "#4",
      name: "Anh Đức",
      points: "10,240 điểm",
      exp: 10240,
      trend: "up",
      isCurrentUser: false,
      category: "Challenge",
      timeframe: "this-week",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-5",
      rank: "#5",
      name: "Bạn (Tôi)",
      points: "9,850 điểm",
      exp: 9850,
      trend: "same",
      isCurrentUser: true,
      category: "Tổng xếp hạng",
      timeframe: "this-week",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-6",
      rank: "#6",
      name: "Lan Hương",
      points: "9,420 điểm",
      exp: 9420,
      trend: "down",
      isCurrentUser: false,
      category: "Contest",
      timeframe: "this-month",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-7",
      rank: "#7",
      name: "Quốc Bảo",
      points: "9,100 điểm",
      exp: 9100,
      trend: "up",
      isCurrentUser: false,
      category: "Streak",
      timeframe: "this-week",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-8",
      rank: "#8",
      name: "Thùy Trang",
      points: "8,950 điểm",
      exp: 8950,
      trend: "up",
      isCurrentUser: false,
      category: "Roadmap",
      timeframe: "all-time",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-9",
      rank: "#9",
      name: "Gia Huy",
      points: "8,700 điểm",
      exp: 8700,
      trend: "down",
      isCurrentUser: false,
      category: "Challenge",
      timeframe: "this-month",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-10",
      rank: "#10",
      name: "Phương Thảo",
      points: "8,520 điểm",
      exp: 8520,
      trend: "same",
      isCurrentUser: false,
      category: "Contest",
      timeframe: "this-week",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-11",
      rank: "#11",
      name: "Tuấn Kiệt",
      points: "8,300 điểm",
      exp: 8300,
      trend: "up",
      isCurrentUser: false,
      category: "Streak",
      timeframe: "all-time",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-12",
      rank: "#12",
      name: "Ngọc Mai",
      points: "8,150 điểm",
      exp: 8150,
      trend: "down",
      isCurrentUser: false,
      category: "Roadmap",
      timeframe: "this-month",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-13",
      rank: "#13",
      name: "Nhật Minh",
      points: "7,900 điểm",
      exp: 7900,
      trend: "up",
      isCurrentUser: false,
      category: "Challenge",
      timeframe: "this-week",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-14",
      rank: "#14",
      name: "Thanh Hằng",
      points: "7,650 điểm",
      exp: 7650,
      trend: "same",
      isCurrentUser: false,
      category: "Contest",
      timeframe: "all-time",
      avatarUrl: heroUrl,
    },
    {
      id: "leaderboard-15",
      rank: "#15",
      name: "Hữu Phước",
      points: "7,400 điểm",
      exp: 7400,
      trend: "up",
      isCurrentUser: false,
      category: "Streak",
      timeframe: "this-week",
      avatarUrl: heroUrl,
    },
  ],

  guides: [
    {
      id: "leaderboard-guide-1",
      title: "Giải challenge",
      description: "Hoàn thành các thử thách lập trình hàng ngày để nhận điểm thưởng lớn.",
      iconName: "Star",
    },
    {
      id: "leaderboard-guide-2",
      title: "Thi đấu contest",
      description: "Tham gia các giải đấu hàng tuần và đánh bại đối thủ để bứt phá thứ hạng.",
      iconName: "Trophy",
    },
    {
      id: "leaderboard-guide-3",
      title: "Giữ streak",
      description: "Duy trì học tập mỗi ngày để nhận số nhân điểm thưởng (Multiplier).",
      iconName: "Flame",
    },
    {
      id: "leaderboard-guide-4",
      title: "Hoàn thành roadmap",
      description: "Tích lũy khối lượng điểm khổng lồ khi kết thúc một mốc lộ trình.",
      iconName: "Compass",
    },
  ],

  faqs: [
    {
      id: "leaderboard-faq-1",
      question: "Bảng xếp hạng được cập nhật bao lâu một lần?",
      answer:
        "Bảng xếp hạng được tính toán và cập nhật thời gian thực ngay sau mỗi lượt nộp bài hoặc hoàn thành bài học.",
    },
    {
      id: "leaderboard-faq-2",
      question: "Làm thế nào để tăng điểm EXP trên bảng xếp hạng?",
      answer:
        "Bạn có thể tích lũy điểm EXP bằng cách giải các bài tập Challenge, thi đấu Contest và duy trì chuỗi học tập Streak.",
    },
    {
      id: "leaderboard-faq-3",
      question: "Top 3 người đứng đầu sẽ nhận được phần thưởng gì?",
      answer:
        "Top 3 hàng tháng sẽ nhận được huy hiệu danh dự đặc biệt và tài khoản LearnFlow Plus miễn phí.",
    },
  ],
};
