# Generated by Django Migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='author_name',
            field=models.CharField(blank=True, default='FySet Team', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(default='Array & Hashing', max_length=100),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testcase',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
