# Generated by Django Migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_problem_code_problem_topic_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
